# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true

- script: echo Hello, world , I am Mounika!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project. Mounika
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

-   task: AzureCLI@2
    enabled: false
    inputs:
      azureSubscription: 'appservice'
      scriptType: 'pscore'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az --version
        az account show
        git --version
- task: Bash@3
  enabled: false
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      git config --global user.email "mounika.azure2022@gmail.com"
      git config --global user.name "mounika pathipka"
      git checkout -b master

      git pull
      echo 'new file '`date` >> testfile.txt
      git add .
      git commit -m "adding new file via CD"
      # git push origin HEAD:master
  displayName: 'Adding report to Git'
- task : Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global user.email "mounika.azure2022@gmail.com"
      git config --global user.name "mounikapathipka"
      git checkout -b master
      echo "removing the file from repo branch"
      rm -rf "testfile.txt"
      git add .
      git commit -m "removing the file"
- powershell: |
    ## get the branch name
    BRANCH_NAME=$(echo "$(System.PullRequest.TargetBranch)" | awk -F/ '{print $NF}')
    ## check branch name starts with HF- or US- or BugFix- .. etc
    $BRANCH_NAME_STARTS_WITH_ARR = @('HF-','US-','BugFix-');
    $IS_VALID_BRANCH= FALSE;
    foreach ($EACH_BRANCH_NAME in $BRANCH_NAME_STARTS_WITH_ARR) {
      if (BRANCH_NAME.StartsWith(EACH_BRANCH_NAME)) {
          $IS_VALID_BRANCH=TRUE;
      }
    }
    ## Get work item from branch name
    ## check work item is present or not
    ## https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/get-work-item?view=azure-devops-rest-6.0&tabs=HTTP
    ## if not present , throw error





