trigger: none
pr:
- main
- releases/*

pool:
  vmImage: 'ubuntu-latest'
steps:
  - bash: |
      az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
      pr_title="$(curl --silent -u azdo:$SYSTEM_ACCESSTOKEN \
       $(System.CollectionUri)_apis/git/repositories/$(Build.Repository.ID)/pullRequests/$(System.PullRequest.PullRequestId)?api-version=5.1 \
       | jq -r .title)"
      echo 'PR titile is '$pr_title
      echo "##vso[task.setvariable variable=pr_title;]'$pr_title'"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    displayName: Extract pull request title

  - task: PowerShell@2
    displayName: 'Validate the PR title, which will be used as the commit message when merging to the target branch'
    inputs:
      targetType: 'filePath'
      filePath: 'validate_conventional_commit.ps1'
      arguments: '$(pr_title)'
      failOnStderr: true
